nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': # Allow all endpoints
            allow_origin: [ 'http://172.18.0.2:3000' ]
            allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
