version: '3.8'

networks:
  symfony_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://symfony:symfony@postgres:5432/symfony_db"
      DATABASE_URL_TEST: "postgresql://symfony:symfony@postgres:5432/symfony_db_test"
    expose:
      - "9000"
    networks:
      symfony_network:
        ipv4_address: 192.168.1.10

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    restart: always
    depends_on:
      - app
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      symfony_network:
        ipv4_address: 192.168.1.13

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      symfony_network:
        ipv4_address: 192.168.1.11

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      symfony_network:
        ipv4_address: 192.168.1.12

volumes:
  postgres_data: